### ISSUE TITLE
我跑了下 owl-vit,结果和论文不一致，想请问原因是啥？

### ISSUE THREAD

**Issue by hhaAndroid** [shikras/d-cube#7] opened 2023-11-23 07:48 UTC
作者好，我直接跑了你提供的 owl-vit 代码，权重是 google/owlvit-base-patch32，但是结果和论文不一样，高不少，想请问原因可能是啥

```python
oading annotations into memory...
Done (t=0.26s)
creating index...
index created!
Loading and preparing results...
DONE (t=1.20s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=73.66s).
Accumulating evaluation results...
DONE (t=26.02s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.090
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.129
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.096
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.044
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.091
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.107
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.157
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.240
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.245
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.080
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.191
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.285
owl_vit.py:76: RuntimeWarning: Mean of empty slice.
  ap_value = ap[ap > -1].mean()
pt19cu111/lib/python3.8/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
mAP over reference length: short - 0.1035, mid - 0.1005, long - 0.0846, very long - 0.0490
loading annotations into memory...
Done (t=0.17s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.58s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=57.11s).
Accumulating evaluation results...
DONE (t=18.97s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.089
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.129
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.095
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.049
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.093
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.106
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.153
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.232
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.237
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.081
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.189
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.278
mAP over reference length: short - 0.1079, mid - 0.1004, long - 0.0834, very long - 0.0228
loading annotations into memory...
Done (t=0.08s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.59s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=18.02s).
Accumulating evaluation results...
DONE (t=6.77s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.091
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.129
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.098
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.030
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.085
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.110
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.169
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.263
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.269
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.077
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.197
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.305
mAP over reference length: short - 0.0888, mid - 0.1011, long - 0.0882, very long - 0.0816
```

**Comment by Charles-Xie** [comment] 2023-11-30 06:59
Hi,
we use the owlvit-base-patch16 ckpt, which is better than owlvit-base-patch32 for OVD.
<img width="656" alt="image" src="https://github.com/shikras/d-cube/assets/24546725/d12a85d2-2a39-42af-938a-460109f63936">

As noted in our supplementary file, we use a score filtering threshold of 0.1 for owlvit, which is its default value for OVD.
<img width="849" alt="image" src="https://github.com/shikras/d-cube/assets/24546725/87666919-515c-4c70-82e9-fb011078dc93">

We think these two aspects may be the reason for the performance difference (9.0 you reproduced vs 8.6 in our paper for FULL intra-scenario mAP).
It is possible that specific choice of weight to load and threshold can impact the performance of owlvit on $D^3$. Actually, 0.05 or 0.1 may not be the best value and tuning it to be 0.06, 0.07 etc. may be better. We did not investigate this very detailedly as it does not affect the analysis in the paper. We are very thankful for pointing this out.

**Comment by Charles-Xie** [comment] 2024-01-04 03:59
This issue is not active for some time so I'm closing it for now. Feel free to reopen it or open another one if any questions arises.

**Closed by Charles-Xie** 2024-01-04 03:59 UTC
